export const REGISTER_USER_LOAD = "REGISTER_USER_LOAD";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";



export const LOGIN_USER_LOAD = "LOGIN_USER_LOAD";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";





export const CLEAR_SUCCESS_AUTH = "CLEAR_SUCCESS_AUTH";
export const CLEAR_ERRORS_AUTH = "CLEAR_ERRORS_AUTH";


export const CURRENT_USER = "CURRENT_USER";

export const LOGOUT_USER = "LOGOUT_USER";